---
language: java
sudo: false
install: true

jdk:
  - openjdk11
  - openjdk17
  - openjdk19
  - oraclejdk11
  - oraclejdk17
  - oraclejdk19

cache:
  directories:
    - "${HOME}/.m2/repository"

notifications:
  email: true
